### PR TITLE
Type hinting

### PR DESCRIPTION
**Pull request by Bhargavasomu**
## What was wrong?

Fixes Issue #6 

#### Cute Animal Picture

put a cute animal picture link inside the parentheses

### CODE REVIEW

**Comment by Bhargavasomu** [comment]
@pipermerriam I guess even this repository is not registered with `Circle CI`. But please review.

**Comment by pipermerriam** [comment]
Project should now be enabled in circle-ci.

**Comment by Bhargavasomu** [comment]
@pipermerriam I have further modernized the `Circle CI` config file. You can now see the `Circle CI` jobs being executed. Please review. Thankyou.

**Comment by pipermerriam** [comment]
Thanks for your continued contributions.

**Pull request merged**
